### PR TITLE
Splash

### LINKED ISSUE #1: Add the starter-page
- [x] Logo
- [x] Cover Page
- [x] Register

### PR DESCRIPTION
**Pull request by ShiningElektra**
Fix #1

 Add Logo
 Create Cover Page
 Register-Objects

### CODE REVIEW

**Review by mrana17 — APPROVED** [review]
Lgtm 🚀

**Review by mrana17 — COMMENTED** [review]
Maybe you can use other naming for the global colors instead of first second and third.

**Review by fre-ben — APPROVED** [review]
LGTM 👍

**Comment by ShiningElektra** [comment]
Thx :-)

**Pull request merged**
